CMS_3D_Core/CMS_3D_Core/Controllers/ContentsEditController.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using CMS_3D_Core.Models.EDM;


using System.IO;



namespace CMS_3D_Core.Controllers
{
    [Authorize]
    public class ContentsEditController : Controller
    {
        private readonly db_data_coreContext _context;

        public ContentsEditController(db_data_coreContext context)
        {
            _context = context;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> TestThree()
        {
            return View();
        }

        /// <summary>
        /// Show Index of Edit Items Of Articles
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Indexold()
        {
            var assys = await _context.t_articles
                                        .Include(t => t.id_assyNavigation)
                                        .Include(t => t.t_instructions)
                                        .Include(t => t.statusNavigation)
                                        .ToListAsync();
            return View(assys);
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> CreateArticle()
        {


            t_article t_article = new t_article() { id_article = 0, id_assy=0 };

            ViewData["id_assy"] = new SelectList(_context.t_assemblies, "id_assy", "assy_name");
            ViewData["status"] = new SelectList(_context.m_status_articles, "id", "name");

            return View("EditArticleWholeContents", t_article);
        }

        /// <summary>
        /// Show Edit View of Articles
        /// </summary>
        /// <param name="id_article"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditArticleWholeContents(long? id_article)
        {

            if (id_article == null)
            {
                return NotFound();
            }

            t_article t_article = await _context.t_articles
                                          .Include(t => t.t_views)
                                          .Include(t => t.t_instructions)
                                          .Where(m => m.id_article == id_article)
                                          .FirstOrDefaultAsync();

            if (t_article == null)
            {
                return NotFound();
            }


            ViewBag.ResultMsg = TempData["ResultMsg"];
            //return View("EditArticleWholeContentsForAjax", t_article);
            return View("EditArticleWholeContentsForAjax", t_article);

        }

        // POST: Role/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProductInstruction(long id_article, long id_instruct, int id_view, string title, string short_description, long display_order, string memo)
        {
            /*
            if (id_article == null | id_instruct == null)
            {
                return NotFound();
            }*/


            var parameter_id_article = new SqlParameter
            {
                ParameterName = "id_article",
                SqlDbType = System.Data.SqlDbType.BigInt,
                Value = id_article,
            };

            var parameter_create_user = new SqlParameter
            {
                ParameterName = "create_user",
                SqlDbType = System.Data.SqlDbType.NVarChar,
                Value = User.Identity.Name,
            };
            var parameter_ans_result = new SqlParameter
            {
                ParameterName = "ans_result",
                SqlDbType = System.Data.SqlDbType.SmallInt,
                Direction = System.Data.ParameterDirection.Output
            };




            if (ModelState.IsValid)
            {
                try
                {
                    var target = await _context.t_instructions.FindAsync(id_article, id_instruct);
                    if (target == null)
                    {
                        // if object is not in table
                        // do add new item acrion
                        t_instruction t_instruction = new t_instruction();
                        t_instruction.id_article = id_article;
                        t_instruction.id_instruct = id_instruct;
                        t_instruction.id_view = id_view;
                        t_instruction.title = title;
                        t_instruction.short_description = short_description;
                        t_instruction.display_order = display_order;
                        t_instruction.memo = memo;

                        await _context.AddAsync(t_instruction);
                        await _context.SaveChangesAsync();

                        await _context.Database
                            .ExecuteSqlRawAsync("EXEC [dbo].[annotation_display_add] @id_article,@create_user,@ans_result OUTPUT"
                            , parameter_id_article
                            , parameter_create_user
                            , parameter_ans_result);


                        TempData["ResultMsg"] = "AddNew Success";
                        return RedirectToAction("EditArticleWholeContents", new { id_article = id_article });
                    } else
                    {
                        // if object is in table
                        // do update new item acrion
                        target.id_view = id_view;
                        target.title = title;
                        target.short_description = short_description;
                        target.display_order = display_order;
                        target.memo = memo;

                        // Update Db
                        await _context.SaveChangesAsync();


                        TempData["ResultMsg"] = "Update Success";
                        return RedirectToAction("EditArticleWholeContents", new { id_article = id_article });
                    }


                }
                catch(Exception e)
                {
                    TempData["ResultMsg"] = "Update Failed";
#if DEBUG
                    TempData["ResultMsg"] = e.Message;
#endif
                }
            }

            // 更新に失敗した場合、編集画面を再描画
            return View(id_article);
        }




        // POST: Role/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProductAnnotationDisplay(IList<t_annotation_display> list)
        {
            /*
            if (id_article == null | id_instruct == null)
            {
                return NotFound();
            }*/


            if (ModelState.IsValid)
            {
                try
                {
                    foreach(var m in list)
                    {
                        var target = await _context.t_annotation_displays.FindAsync(m.id_article, m.id_instruct, m.id_annotation);
                        target.is_display = m.is_display;
                    }



                    // Update Db
                    await _context.SaveChangesAsync();


                    TempData["ResultMsg"] = "Update Success";
                    return RedirectToAction("EditArticleWholeContents", new { id_article = list[0].id_article });




                }
                catch (Exception e)
                {
                    TempData["ResultMsg"] = "Update Failed";
#if DEBUG
                    TempData["ResultMsg"] = e.Message;
#endif
                }
            }

            // 更新に失敗した場合、編集画面を再描画
            return View(list[0].id_article);
        }
        




        // POST: Role/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProductAnnotation(long id_article, long id_annotation, string title, string description1, string description2, short status, float pos_x, float pos_y, float pos_z)
        {
            /*
            if (id_article == null | id_instruct == null)
            {
                return NotFound();
            }*/


            var parameter_id_article = new SqlParameter
            {
                ParameterName = "id_article",
                SqlDbType = System.Data.SqlDbType.BigInt,
                Value = id_article,
            };

            var parameter_create_user = new SqlParameter
            {
                ParameterName = "create_user",
                SqlDbType = System.Data.SqlDbType.NVarChar,
                Value = User.Identity.Name,
            };
            var parameter_ans_result = new SqlParameter
            {
                ParameterName = "ans_result",
                SqlDbType = System.Data.SqlDbType.SmallInt,
                Direction = System.Data.ParameterDirection.Output
            };




            if (ModelState.IsValid)
            {
                try
                {
                    var target = await _context.t_annotations.FindAsync(id_article, id_annotation);
                    if (target == null)
                    {
                        // if object is not in table
                        // do add new item acrion
                        t_annotation t_annotation = new t_annotation();
                        t_annotation.id_article = id_article;
                        t_annotation.id_annotation = id_annotation;
                        t_annotation.title = title;
                        t_annotation.description1 = description1;

CMS_3D_Core/CMS_3D_Core/Views/Shared/Components/EditProductAnnotationDisplay/_EditProductAnnotationDisplayAjax.cshtml
@*テーブルとして出すのは、instruct毎のdisplayアイテム
    一回ループが回るたびに、javascriptで書き換える*@

@model IEnumerable<CMS_3D_Core.Models.EDM.t_annotation_display>

<div id="id_edit_annotation_display">



    <table class="table">
        <thead>
            <tr>
                <th>
                    No.
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.id_annotation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.id_a.title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.id_a.description1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.is_display)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.is_display_description)
                </th>
            </tr>
        </thead>
        <tbody id="id_edit_annotation_display_tbody">
        </tbody>
    </table>


</div>



@*テーブルとして出すのは、instruct毎のdisplayアイテム
    一回ループが回るたびに、javascriptで書き換える*@

@*
    @model IList<CMS_3D_Core.Models.EDM.t_annotation_display>

    <div id="view_data">


    </div>


    <form asp-controller="ContentsEdit" asp-action="EditProductAnnotationDisplay">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        No.
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].id_annotation)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].id_a.title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].id_a.description1)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].is_display)
                    </th>
                </tr>
            </thead>
            <tbody id="id_edit_annotation_display_tbody">
                @for (int i = 0; i < Model.Count; i++)
                //@foreach (var item in Model)
                {
                    var key = String.Format("[{0}].", Model[i].id_annotation);
                    <tr>
                        <td>
                            @Html.HiddenFor(modelItem => Model[i].id_article, new { id = key + "id_edit_annotation_display_input_id_article" })
                            @Html.HiddenFor(modelItem => Model[i].id_instruct, new { id = key + "id_edit_annotation_display_input_id_instruct" })
                            @Html.HiddenFor(modelItem => Model[i].id_annotation, new { id = key + "id_edit_annotation_display_input_id_annotation" })
                            @Html.DisplayFor(modelItem => Model[i].id_annotation, new { id = key + "id_edit_annotation_display_display_id_annotation" })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model[i].id_annotation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model[i].id_a.title, new { id = key + "id_edit_annotation_display_input_title" })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model[i].id_a.description1, new { id = key + "id_edit_annotation_display_input_description1" })
                        </td>
                        <td>
                            @Html.CheckBoxFor(modelItem => Model[i].is_display, new { id = key + "id_edit_annotation_display_input_is_display" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>


        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" onclick="return confirm('Are you update View?')" />
        </div>
    </form>

*@