CMS_3D_Core/CMS_3D_Core/Controllers/ContentsViewController.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using CMS_3D_Core.Models.EDM;


namespace CMS_3D_Core.Controllers
{
    public class ContentsViewController : Controller
    {
        //private db_data_coreContext db = new db_data_coreContext();

        private readonly db_data_coreContext _context;

        public ContentsViewController(db_data_coreContext context)
        {
            _context = context;
        }

        /// <summary>
        /// GET: コンテンツの一覧TOP画面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            //var assys = _context.t_assemblies;
            //return View(assys.ToList());
            return View();
        }


        /// <summary>
        /// GET: コンテンツを表示する
        /// </summary>
        /// <param name="id_assy"></param>
        /// <returns></returns>
        [HttpGet]
        //public ActionResult DetailProductInstruction(long? id_article)
        public async Task<IActionResult> DetailProductInstruction(long? id_article)
        {

            if (id_article == null)
            {
                return NotFound();
            }

            /*
            var min_display = await _context.t_instructions
                                        .Where(m => id_article == id_article)
                                        .MinAsync(m => m.display_order);

            var temp = await _context.t_instructions
                                        //.OrderBy(t => t.display_order)
                                        .FirstOrDefaultAsync(m => id_article == id_article & m.display_order == min_display);

            int id_view = temp.id_view;
            */

            t_article t_article = await _context.t_articles
                                          .Include(t => t.t_views)//.Where(m => m.id_view == id_view))
                                          .Include(t => t.t_instructions)
                                          .Where(m => m.id_article == id_article & m.statusNavigation.is_approved == true)
                                          .FirstOrDefaultAsync();

            if (t_article == null)
            {
                return NotFound();
            }


            return View(t_article);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CMS_3D_Core/CMS_3D_Core/Controllers/SiteSettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using CMS_3D_Core.Models.EDM;

namespace CMS_3D_Core.Controllers
{
    [Authorize]
    public class SiteSettingController : Controller
    {
        private readonly db_data_coreContext _context;

        public SiteSettingController(db_data_coreContext context)
        {
            _context = context;
        }

        // GET: SiteSetting
        public async Task<IActionResult> Index()
        {
            return View(await _context.t_website_settings.ToListAsync());
        }

        // GET: SiteSetting/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var t_website_setting = await _context.t_website_settings
                .FirstOrDefaultAsync(m => m.title == id);
            if (t_website_setting == null)
            {
                return NotFound();
            }

            return View(t_website_setting);
        }

        // GET: SiteSetting/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SiteSetting/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("title,data,memo")] t_website_setting t_website_setting)
        {
            if (ModelState.IsValid)
            {
                _context.Add(t_website_setting);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(t_website_setting);
        }

        // GET: SiteSetting/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var t_website_setting = await _context.t_website_settings.FindAsync(id);
            if (t_website_setting == null)
            {
                return NotFound();
            }
            return View(t_website_setting);
        }

        // POST: SiteSetting/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("title,data,memo")] t_website_setting t_website_setting)
        {
            if (id != t_website_setting.title)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(t_website_setting);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!t_website_settingExists(t_website_setting.title))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(t_website_setting);
        }

        // GET: SiteSetting/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var t_website_setting = await _context.t_website_settings
                .FirstOrDefaultAsync(m => m.title == id);
            if (t_website_setting == null)
            {
                return NotFound();
            }

            return View(t_website_setting);
        }

        // POST: SiteSetting/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var t_website_setting = await _context.t_website_settings.FindAsync(id);
            _context.t_website_settings.Remove(t_website_setting);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool t_website_settingExists(string id)
        {
            return _context.t_website_settings.Any(e => e.title == id);
        }
    }
}

CMS_3D_Core/CMS_3D_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 3D Aerospace Museum</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />

    *@
    <script src="~/js/dist/layout.bundle.js" defer></script>
    <meta name="description" content="@ViewData["MetaDescription"]" />

    @await Component.InvokeAsync("ShowHtmlTag", new { title = "GoogleAnalyticsSettings" })

    @if (ViewData["ShowGoogleAdSenseAdvertisement"] == "ON")
    {
        @await Component.InvokeAsync("ShowHtmlTag", new { title = "GoogleAdSenseAdvertisement" })
    }

</head>


@*<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">*@

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">3D Aerospace Museum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarCollapse">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @Html.ActionLink("Contents", "Index", "ContentsView", null, new { @class = "nav-link" })
                        </li>
                        <partial name="_NavbarPartial" />
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - 3D Aerospace Museum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    *@
    @*
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CMS_3D_Core/CMS_3D_Core/Views/Shared/_NavbarPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@if (SignInManager.IsSignedIn(User))
{
        <li class="nav-item">
         @*   @Html.ActionLink("ContentsEdit", "Index", "ContentsEdit", null, new { @class = "nav-link" })  *@
            <a class="nav-link" asp-area="" asp-controller="ContentsEdit" asp-action="Index">ContentsEdit</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="SiteSetting" asp-action="Index">SiteSetting</a>
        </li>        
}
else
{
}